version: "3.8"
services:
  fe:
    image: "${IMAGE_NAME}"
    deploy:
      replicas: 3
    networks:
      - frontend-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - fe

networks:
  frontend-network:
    driver: bridge
